[tool.black]
line-length = 80
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.vscode
    | \.tox
    | .venv
    | env
    | venv
    | build
    | dist
  )/
)
'''
